### PR TITLE
Don't crash if the query params are invalid json

### PR DESCRIPTION
**Pull request by akcoder**
Fixes a crash that occurs if the json query string parameters are invalid

### CODE REVIEW

**Comment by zaidka** [comment]
Thanks. Responding with status code 400 would be ideal, but simply letting a crash to happen and respond with 500 is not that bad and it's definitely better than silently ignoring errors.

**Comment by akcoder** [comment]
Fair enough. I'll switch it to throw a 400 when I get back to the office. Won't be for 3 days though. 

-dan

**Comment by akcoder** [comment]
I've updated the change to return a 400.

**Comment by zaidka** [comment]
Thanks!

**Pull request merged**
