### PR TITLE
Add config option to bind UDP port to STUN port, allowing UDP Connection Requests to originate from a port shared with the local STUN server.

### PR DESCRIPTION
**Pull request by spencerlambert**
Some devices report a value of "Enabled" or "Disabled" as a bool type.  This adds support for these devices.

### CODE REVIEW

**Comment by spencerlambert** [comment]
I added some code that makes UDP work with a STUN server.  I could put these into a different pull request if only `df2ebb0` is good.

**Comment by zaidka** [comment]
Is the parameter type xsd:boolean? I've seen some devices use Enabled/Disabled but as string types. Regardless, this is not standard and the current implementation shows a warning when it fails to parse it and keeps the original value as a string. I believe that's a better approach than silently accepting non standard values.

**Comment by spencerlambert** [comment]
Yes it reports it as boolean type.  I can respect not wanting to convert something that is non-standard.  Before the 1.1 release, it crashed at the boolean parse function.  I can live with a warning and the original string value.

Do you have any thoughts on the port binding to make STUN work?

**Comment by zaidka** [comment]
> Do you have any thoughts on the port binding to make STUN work?

I remember at the time trying something similar to what you've done but I kept getting "address in use" error even with the reuseAddr flag. Can you confirm your changes work when you have a stun server listening to the same port?

In my testing I used this STUN server implementation https://sourceforge.net/projects/stun/ and had to run it with -m flag to make it act as a proxy so that the packets are sent from the same source IP and port as the STUN server.

**Comment by spencerlambert** [comment]
At first I was getting the "address in use" error.  I figured the STUN server I wasn't setting the SO_REUSEADDR option for it's connection.

I'm using this STUN server: https://sourceforge.net/projects/stuntman/

After a short code review I found this line: https://github.com/jselbie/stunserver/blob/master/networkutils/stunsocket.cpp#L324

The last arg is `false` which prevents the SO_REUSEADDR option: https://github.com/jselbie/stunserver/blob/master/networkutils/stunsocket.cpp#L296-L301

Changing the argument to `true` and re-compiling the STUN server allowed both Genieacs and STUN to bind to the same port at the same time.

**Comment by zaidka** [comment]
That's interesting. Though in that case rather than using the port number from STUNServerPort parameter, it might make more sense to have that as a configuration option. What do you think?

Another potential solution is to use iptables rules to change the source port of the outgoing packet. I played with that a little bit at the time but couldn't get it to work given my limited experience with iptables.

**Comment by spencerlambert** [comment]
A config option would work, it might even be preferable, as the user can ensure that both the STUN server and Genieacs are setup proper, allowing for on demand changes if needed, not relying on what the value happens to be set in STUNServerPort.  A config option may prove to be more reliable.

I checked the source on another STUN server; coturn.  It looks to properly set the SO_REUSEADDR option.

https://github.com/coturn/coturn/blob/114881bc9a455b8694634dd4cc3c3acb22845826/src/apps/common/apputils.c#L158-L171

I'm testing it now and will let you know how it goes.

**Comment by spencerlambert** [comment]
Coturn (https://github.com/coturn/coturn) works out of the box, setting the SO_REUSEADDR option.

I ran it with these options: `turnserver -Sv`
S = STUN Only Mode
v = Verbose Output

**Comment by spencerlambert** [comment]
I'm modifying this pull request to set use a config option for setting the UDP port.

**Comment by spencerlambert** [comment]
I've updated the pull request, modifying it to just adding a config option to set UDP port binding.

As a side note, this is an example of a `boolean` type with a value `Enabled`.  Totally non-standard, but ¯\_(ツ)_/¯.
screenshot from 2017-03-25 13-32-52

**Comment by zaidka** [comment]
A few comments:

- Make sure to close the socket.
- Use "exclusive" flag when binding the socket. Could you please also test that two worker processes calling bind at the same time will not cause an error (assuming reuseAddr is true).
- Use a single configuration option (e.g. UDP_CONNECTION_REQUEST_PORT). If value is 0 (default) then don't do explicit binding.
- No need to include this in the sample config file as it's not commonly used.

**Comment by spencerlambert** [comment]
Yes, I'll make these improvements.

BTW, I'm also working on a pull request for the Stuntman STUN Server.

https://github.com/jselbie/stunserver/pull/20

This will add a `--reuseaddr` command line switch to make the `reuseAddr` Genieacs option work with the Stuntman STUN server.

**Comment by zaidka** [comment]
I did some tests and it turns out that when you bind to a port that's already in use, the original process will no longer receive messages on that port. In other words, binding to port 3478 will probably cause the STUN server to not function properly.

**Comment by spencerlambert** [comment]
Interesting, that might be related to some behavior I was seeing, where I couldn't do two UDP Connection Requests close together.  UDP messages stop working, until the router pinged the STUN server a couple of times.

I'll do more testing and research, seeing if there is a way to prevent this.

**Comment by spencerlambert** [comment]
The socket gets closed here: https://github.com/spencerlambert/genieacs/blob/c173120427d43ef48b275eee71a8f8c61ab5aa6b/lib/api-functions.coffee#L59

**Comment by spencerlambert** [comment]
I was looking at the STUN server on a commercial ACS.  From what I can tell, they are using a modified version of the STUN server you are testing with (https://sourceforge.net/projects/stun/), but have added a `-r relayport` option.

## Output of --help from Commercial ACS STUN Server
```
STUN server version 0.96
Usage: 
./server [-v] [-h] [-h IP_Address] [-a IP_Address] [-p port] [-o port] [-m mediaport] [-r relayport] 

If the IP addresses of your NIC are 10.0.1.150 and 10.0.1.151, run this program with 
./server -v  -h 10.0.1.150 -a 10.0.1.151

STUN servers need two IP addresses and two ports, these can be specified with:  
-h sets the primary IP  
-a sets the secondary IP  
-p sets the primary port and defaults to 3478  
-o sets the secondary port and defaults to 3479  
-b makes the program run in the backgroud  
-m sets up a STERN server starting at port m  
-r sets the relay port  
-v runs in verbose mode
```

Comparing the output of --help shows the similarities between the Commercial ACS STUN Server and the opensource project, even down to the miss-spelling of background.

https://sourceforge.net/p/stun/code/HEAD/tree/stund/tags/v0.96/server.cxx#l25

I'm not sure how the `-m` switch differs from what they are doing with `-r`.  I know you already said that you had GenieACS working with the `-m` switch, so I'll give this a try now.

**Comment by spencerlambert** [comment]
The `-m` option using https://sourceforge.net/projects/stun/ kinda works.  The initial UDP Connection Request goes fine, but follow up ones do not, unless I wait about 10 seconds.  I'm not sure what that is about.  Have you seen this behavior?  It might be a device issue, because I do see the relay messages in the STUN server output.

**Comment by zaidka** [comment]
The -m flag sets a relay given a range of ports. If I have to guess I'd say they implemented the -r flag to somehow work around the limitation of using STERN where you're limited by the number of ports available so you can't handle more than a few thousand devices per STUN server instance.

I remember facing a similar issue where I needed to wait a few seconds before sending another connection request. I couldn't figure out what might be causing that so I ruled it out as a device issue. It was a Huawei device so if you're seeing this issue on a device from a different manufacturer then it might be worth revisiting the issue.

**Comment by spencerlambert** [comment]
I'll need to get past the few thousand device per STUN server instance limit.  I'm working with the Stuntman developer and maybe a message relay feature would be easy to add.

I'm testing devices manufactured by ReadyNet.  I've also not see this missed message issue with my current commercial ACS and STUN installation. I'll do some testing, seeing if I can prove if the missed message are device related or not, narrowing down what the problem is.

**Comment by spencerlambert** [comment]
What do you think of option 2 for sending UDP messages to devices?

https://github.com/jselbie/stunserver/pull/20#issuecomment-289611040

**Comment by zaidka** [comment]
> What do you think of option 2 for sending UDP messages to devices?

Looks like it'll be a custom protocol between genieacs and stunserver. Can't say I'm a fan of that approach to be honest.

Have you tried fiddling with iptables as I suggested above?

**Comment by spencerlambert** [comment]
> Looks like it'll be a custom protocol between genieacs and stunserver.

That's a good point.  I'll be testing with iptables tomorrow.

**Comment by jselbie** [comment]
I think the approach should be as follows:

1. Figure out why,even with socket option reuseAddr being using both processes does this mess things up. (And is there a workaround and/or iptables solution?)

2. Failing a workaround for #1, build the stun server directly into genieACS. There's several STUN servers already written in Node. You could probably just drop the code in and then come up with some way to share the socket with the ACS code that needs to send with it.

3. If #1 and #2 are ruled out, then do the custom relay protocol between GenieACS and Stuntman.  (What Spencer and I talked about on the other thread - have GenieACS usea random port to send a STUN indication message to Stuntman, then Stuntman forwards the payload to the client device).  And by custom, I mean, "a new open standard for how ACS servers and share socket resources".  :)

I looked at why #1 is using Linux box. I did some experiments with running Stuntman with SO_REUSEADDR flag and a simple node program that creates a dgram socket.  I couldn't repro the issue Spencer called out where the stuntman process would lose packets, but according to the Node documentation:

> Once the socket is created, calling socket.bind() will instruct the socket to begin listening for datagram messages.

I validated that the "listening" callback is fired on a dgram socket the moment "bind" is called. This implies that Node is likely registering a select/epoll call on the socket and at least attempting to get at the messages even when there is no registered "message" callback.  And I do know when two processes are listening on the same port, one of them will win when an incoming UDP packet arrives.  But we're probably in "undefined" territory here as to which process wins.  So I might rule out that the processes can share the socket reliably.

I've used iptables before, but a quick internet search shows it can block packets based on process id.  So that might be the way to go.

Zaid - you might want to consider #2 above.  That would make GenieACS a more complete solution and you could probably just paste the code in to register a stun socket listener, message handler, and then some way to share the socket.

#3 is interesting from an integration perspective if #2 isn't desired.

Let me know if I can help.

**Comment by spencerlambert** [comment]
So far iptables isn't looking good. 

First I tried doing a simple DNAT rule, with Node sending UDP packets on port 7502.
```
iptables -t nat -A POSTROUTING -p udp -m udp --sport 7502 -j SNAT --to-source :3478
```

The rule is working, as the rule packet counter increases.
```
Chain POSTROUTING (policy ACCEPT 22 packets, 1474 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    1   198 SNAT       udp  --  any    any     anywhere             anywhere             udp spt:7502 to::3478
```

Node gives this error when sending the UDP Connection Request packet.
```
2017-03-28T22:17:50.764Z [ERROR] Uncaught exception; exceptionName="Error" exceptionMessage="send EPERM 70.70.70.70:43232" exceptionStack="Error: send EPERM 70.70.70.70:43232\n    at Object.exports._errnoException (util.js:1022:11)\n    at exports._exceptionWithHostPort (util.js:1045:20)\n    at SendWrap.afterSend [as oncomplete] (dgram.js:407:11)"
2017-03-28T22:18:20.776Z [ERROR] Worker died; pid=2731 exitCode=1
```

If I change the SNAT rule to a port other than 3478, the Connection Request packet is sent over the SNAT port and I get no Node error, but obviously the packet is being sent from the wrong port.

I tried other variations, like putting STUN on port 7501 and doing SNAT and DNAT rules.  STUN functioned fine in this state, but I got the same error in Node.  I'm thinking something inside iptables is seeing the ambiguity and rejecting the SNAT rule.

**Comment by spencerlambert** [comment]
I re-tested the code that lets both GenieACS and STUN use the same 3478 port.  Based on a packet capture I did from the NAT'ed CPE it received 100% of the UDP messages.  The issue with the UDP Connection Request not having an affect, causing the CPE to make an inform doesn't look like it's an issue with sharing the port between GenieACS and STUN.

I'm thinking it's one of two things: 1) an issue with the CPE, or 2) an issue with the Connection Request message.

Here is my packet capture.  Close together, I did three API calls to GenieACS, with Node JS sending three UDP Connection Requests messages each time, for a total of nine.  The CPE received all nine UDP messages.

screenshot from 2017-03-28 18-03-17

**Comment by spencerlambert** [comment]
I've been able to reproduce the same ignored UDP Connection Request issue using a commercial ACS.  It could be that some CPEs simple limit the frequency of UDP Connection Requests they will respond to as may be an anti-attack mechanism.

Any way, the commercial CPE handles the situation by making a single new UDP Connection Request every 30-60 second while there are pending tasks.  This is the packet capture on the commercial ACS. The packet highlighted is the UDP Connection Request ignored by the CPE.

screenshot from 2017-03-29 10-47-10

I'm thinking that doing something similar in GenieACS is a good sound approach, as there could be many reasons a CPE has not responded to a UDP Connection Request, besides a CPE is ignoring them. What are your thoughts on having GenieACS slowly send UDP Connection Requests while there are pending tasks?

**Comment by spencerlambert** [comment]
This simple change would improve the reliability of getting devices to complete needed tasks.

After line 296 in `/lib/nbi.coffee`, call a new function, possibly named `watchTaskBackground()`.

https://github.com/zaidka/genieacs/blob/6f45042c52c42204e9c58829b7dad339a233e02b/lib/nbi.coffee#L296

`watchTaskBackground()` would work similar to `watchTask()`, but it would run once every 45 sec, issuing a new UDP Connection Requests, if the task has not finished, giving up after 5-10 minutes.

What are your thoughts?

**Comment by spencerlambert** [comment]
This is a change to `watchTask()`, adding `options`, allowing it to continue to slowly watch a task while making follow up connection requests.  In my testing, I've been able to reliably get tasks finished on NAT'ed devices.

https://github.com/spencerlambert/genieacs/commit/8bbef3778ca35fa59b54c73547165465f7709186

Some config parameters would be nice for setting, should do background watch, background watch timeout, and check delay.

**Comment by zaidka** [comment]
Thanks @jselbie for chiming in. The current solution using a relay is actually not that bad. The only limitation is having to deploy more than one STUN server instance if the total number of devices is more than the number available ports (60k?). With that in mind, I don't think it's worthwhile to implement a nonstandard integration or maintain our own integrated STUN implementation.

**Comment by zaidka** [comment]
@spencerlambert, it's odd that it crashes when you have iptables rules. But I'm no expert in that anyway. You can try doing something similar using some other language like Perl. If you manage to get that to work then we can write a C code in Genie that handles this trickery.

The UDP connection request delay is not related to this PR so let's discuss that separately in the mailing list or another PR if you prefer.

**Comment by spencerlambert** [comment]
The `UDP_CONNECTION_REQUEST_PORT` is working for me.  As I've already shown with my packet capture, every sent packet from both Node and STUN are making it to the CPE, with the `UDP_CONNECTION_REQUEST_PORT` set to 3478.

I was a little hasty and added a background task watcher to this pull request.  Sorry, I missed your comment.  I can pull it out if you'd like to proceed with the `UDP_CONNECTION_REQUEST_PORT` part.

I've given up on making iptables work.  I'm not going to do any Perl stuff, especially because my current `UDP_CONNECTION_REQUEST_PORT` option is working.

I think the background task watcher is related, because the goal of the `UDP_CONNECTION_REQUEST_PORT` option is to get STUN working.  For STUN to work, the ACS needs to reliably get UDP Connection Requests to a NAT'ed CPE.  We've both seen that CPEs may ignore UDP Connection Requests when they are too close together.

Anyways, I'm happy to make a separate pull request.

**Comment by zaidka** [comment]
> The UDP_CONNECTION_REQUEST_PORT is working for me.

In my tests I found that once you bind to a port that's already used by another process (using reuseAddr), the original process will not receive packets anymore until you unbind. So yes the device will receive UDP requests just fine, but during that brief moment the STUN server will not be reachable when any device tries to communicate with it.

As for the background watcher, I don't see much benefit in attempting to run the tasks after the API has already responded that the tasks cannot be executed because the device is not reachable. You can implement something similar on top of the API anyway.

**Comment by spencerlambert** [comment]
> In my tests I found that once you bind to a port that's already used by another process (using reuseAddr), the original process will not receive packets anymore until you unbind. 

Right now, I see no way of fixing this, so I'm closing this pull request.  Personally, I'm okay with blocking the STUN server for a few milliseconds.  The UDP Connection Request is the highest priority traffic at that moment and STUN survives the momentary blocking.  The CPEs are constantly checking in with the STUN server, so a momentary block has the same affect as a dropped packet, none.

**Comment by jselbie** [comment]
@zaidka  - regarding the port limit.  When you say:

> The only limitation is having to deploy more than one STUN server instance if the total number of devices is more than the number available ports (60k?). 

That's not correct from my perspective. Because a minimal STUN server only occupies a single UDP port (typically port 3478) that an infinite number of devices can interact with.  The capacity of a UDP datagram service isn't based on port availability, it's simply the capacity of the network and server hardware itself.

Based on my understanding of how ACS utilizes STUN, the STUN server needs to be on the same box anyway (otherwise, the client device's NAT will not know how to forward it).

The 64K limit you are referring to are the number of unique ports number - and typically only applies to client devices.  If it was theoretically possible for a client to simultaneously have 64K connections to different hosts, it could run out of ports itself.   But a TCP *server* always uses the *same* port to host *multiple* connections to different remote client IP\port addresses.  A TCP server could host 100K or more connections if it wasn't for the fact that OS loads gets heavy at the 10K connection level and that most socket coders are spawning threads for every connection and/or using an inefficient select/poll mechanism.  All of these problems are exactly that Node.JS was designed to address.

**Comment by zaidka** [comment]
> The CPEs are constantly checking in with the STUN server, so a momentary block has the same affect as a dropped packet, none.

 Hmm, that's a good point. Please go ahead and update the PR for this. Let's see if Jon is willing to support SO_REUSEADDR in Stuntman.

> That's not correct from my perspective. Because a minimal STUN server only occupies a single UDP port (typically port 3478) that an infinite number of devices can interact with. The capacity of a UDP datagram service isn't based on port availability, it's simply the capacity of the network and server hardware itself.

 I'm referring to the use of relay where every port is mapped to a single device. Not sure if this is implemented in Stuntman, but this project supports setting a relay (see -m flag): https://sourceforge.net/projects/stun/

**Comment by spencerlambert** [comment]
For anyone following along, I've created a [cleaner pull request](https://github.com/zaidka/genieacs/pull/221) that doesn't have the background task watcher I hastily added.

**Comment by spencerlambert** [comment]
> Let's see if Jon is willing to support SO_REUSEADDR in Stuntman.

Hopefully Jon adds support, but regardless other STUN servers already work and support it, like [coturn](https://github.com/coturn/coturn).

**Comment by jselbie** [comment]
@spencerlambert  - your `SO_REUSEADDR` change is getting merged in this weekend.  There's a side-effect that I need to investigate, but it shouldn't stop this from happening.

@zaidka  - that `-m` thing they do on that other code base server is an interesting ~~hack~~ non-standard implementation for doing a relay server.  (It's also very insecure as they have it implemented and would be an easy target for a DOS attack).

**Pull request closed without merging**
